In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix

In [2]:
x= torch.empty(5,3)
print(x)

tensor([[4.7393e+30, 9.5461e-01, 4.4377e+27],
        [1.7975e+19, 4.6894e+27, 7.9463e+08],
        [3.2604e-12, 1.7743e+28, 2.0535e-19],
        [5.9682e-02, 7.0374e+22, 3.8946e+21],
        [4.4650e+30, 7.0975e+22, 7.9309e+34]])


Construct a randomly initialized matrix

In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.9719, 0.1851, 0.9302],
        [0.5373, 0.4720, 0.3252],
        [0.7811, 0.1406, 0.5516],
        [0.1868, 0.9880, 0.1711],
        [0.3640, 0.8854, 0.1644]])


Construct a matrix filled zeros and dtype long

In [4]:
x= torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data

In [5]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor based on an existing tensor

In [6]:
x=x.new_ones(5,3, dtype=torch.double)
print(x)

x=torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.7108, 0.9131, 0.5083],
        [0.9494, 0.4746, 0.2735],
        [0.2030, 0.2653, 0.2561],
        [0.3857, 0.4295, 0.1822],
        [0.4191, 0.4747, 0.2400]])


Gets its size

In [7]:
print(x.size())

torch.Size([5, 3])


Addition operation: syntax 1

In [8]:
y= torch.rand(5,3)
print(x+y)

tensor([[1.5113, 0.9234, 0.6203],
        [1.1307, 0.8118, 1.2269],
        [1.1870, 1.0018, 1.1261],
        [1.1527, 0.9869, 0.3095],
        [1.0115, 1.3733, 0.8471]])


Addition operation: syntax 2

In [9]:
print(torch.add(x,y))

tensor([[1.5113, 0.9234, 0.6203],
        [1.1307, 0.8118, 1.2269],
        [1.1870, 1.0018, 1.1261],
        [1.1527, 0.9869, 0.3095],
        [1.0115, 1.3733, 0.8471]])


Addition operation: providing an output tensor as argument

In [10]:
result=torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[1.5113, 0.9234, 0.6203],
        [1.1307, 0.8118, 1.2269],
        [1.1870, 1.0018, 1.1261],
        [1.1527, 0.9869, 0.3095],
        [1.0115, 1.3733, 0.8471]])


Addition operation: in-place

In [11]:
y.add_(x)
print(y)

tensor([[1.5113, 0.9234, 0.6203],
        [1.1307, 0.8118, 1.2269],
        [1.1870, 1.0018, 1.1261],
        [1.1527, 0.9869, 0.3095],
        [1.0115, 1.3733, 0.8471]])


In [12]:
print(x[:,1])

tensor([0.9131, 0.4746, 0.2653, 0.4295, 0.4747])


Resizing/reshape tensor

In [13]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


get tensor value 

In [14]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([0.0257])
0.025715753436088562


Numpy bridge

Converting a torch tensor to a Numpy array

In [15]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Convert a Numpy Array to Torch Tensor

In [18]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CUDA Tensor

In [19]:
if torch.cuda.is_available():
    devide=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu", torch.double))