In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix

In [8]:
x=torch.empty(5,3)
print(x)

tensor([[-1.9259e-21,  3.0736e-41,  1.3593e-43],
        [ 0.0000e+00, -1.9450e-21,  3.0736e-41],
        [-3.5212e+28,  4.5595e-41, -1.9257e-21],
        [ 3.0736e-41, -5.7240e+07,  4.5595e-41],
        [-5.8697e+14,  4.5595e-41, -5.7303e+07]])


Construct a randomly initialized matrix

In [9]:
x=torch.rand(5,3)
print(x)

tensor([[0.2395, 0.4107, 0.2441],
        [0.6073, 0.3839, 0.9470],
        [0.0873, 0.4694, 0.8356],
        [0.1135, 0.9456, 0.3213],
        [0.5421, 0.2249, 0.4318]])


Construct a matrix filled zeros and dtype long

In [11]:
x=torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data

In [12]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor based on an existing tensor

In [13]:
x=x.new_ones(5,3, dtype=torch.double)
print(x)

x=torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.4124, 0.4645, 0.6989],
        [0.4422, 0.7868, 0.5001],
        [0.7228, 0.0837, 0.9090],
        [0.2034, 0.7836, 0.1196],
        [0.1083, 0.4699, 0.0204]])


Gets its size

In [15]:
print(x.size())

torch.Size([5, 3])


Addition operation: syntax 1

In [16]:
y=torch.rand(5,3)
print(x+y)

tensor([[1.0132, 0.7758, 1.5983],
        [1.1100, 1.0695, 1.4967],
        [1.1665, 0.9753, 1.8640],
        [0.5142, 1.7535, 0.5399],
        [0.7005, 1.2459, 0.7023]])


Addition operation: syntax 2

In [18]:
print(torch.add(x,y))

tensor([[1.0132, 0.7758, 1.5983],
        [1.1100, 1.0695, 1.4967],
        [1.1665, 0.9753, 1.8640],
        [0.5142, 1.7535, 0.5399],
        [0.7005, 1.2459, 0.7023]])


Addition operation: providing an output tensor as argument

In [19]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.0132, 0.7758, 1.5983],
        [1.1100, 1.0695, 1.4967],
        [1.1665, 0.9753, 1.8640],
        [0.5142, 1.7535, 0.5399],
        [0.7005, 1.2459, 0.7023]])


Addition operation: in-place

In [20]:
y.add(x)

tensor([[1.0132, 0.7758, 1.5983],
        [1.1100, 1.0695, 1.4967],
        [1.1665, 0.9753, 1.8640],
        [0.5142, 1.7535, 0.5399],
        [0.7005, 1.2459, 0.7023]])

In [42]:
x=torch.rand(5,3)
print(x)
print(x[:1])
print(x[:,0])
print(x[0,0].item())

tensor([[0.2604, 0.8868, 0.3061],
        [0.7360, 0.2075, 0.8502],
        [0.1636, 0.6505, 0.3555],
        [0.5755, 0.1581, 0.5229],
        [0.2951, 0.8782, 0.0599]])
tensor([[0.2604, 0.8868, 0.3061]])
tensor([0.2604, 0.7360, 0.1636, 0.5755, 0.2951])
0.2604471445083618


Resizing/reshape tensor

In [27]:
x=torch.rand(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


get tensor value 

In [28]:
x=torch.rand(1)
print(x)
print(x.item())

tensor([0.3044])
0.30438321828842163


Numpy bridge

Converting a torch tensor to a Numpy array

In [43]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [44]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [45]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Convert a Numpy Array to Torch Tensor

In [50]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CUDA Tensor

In [52]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[1.2604, 1.8868, 1.3061],
        [1.7360, 1.2075, 1.8502],
        [1.1636, 1.6505, 1.3555],
        [1.5755, 1.1581, 1.5229],
        [1.2951, 1.8782, 1.0599]], device='cuda:0')
tensor([[1.2604, 1.8868, 1.3061],
        [1.7360, 1.2075, 1.8502],
        [1.1636, 1.6505, 1.3555],
        [1.5755, 1.1581, 1.5229],
        [1.2951, 1.8782, 1.0599]], dtype=torch.float64)
